"""add practice, analysis, weaknesses and persona tables

Revision ID: cd5634f0fa16
Revises: 35526200c083
Create Date: 2026-09-11 17:00:31.293244+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "cd5634f0fa16"
down_revision: str | None = "35526200c083"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="in_progress", nullable=False
        ),
        sa.Column("transcript", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed', 'incomplete')",
            name="ck_learning_sessions_status",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_sessions_user_id"),
        "learning_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "persona_memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.String(length=100), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "scenario_id", name="uq_persona_memories_user_scenario"
        ),
    )
    op.create_index(
        op.f("ix_persona_memories_user_id"),
        "persona_memories",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "session_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "grammar_findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "vocabulary_findings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "fluency_findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "task_completion", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "focus_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["learning_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_session_analyses_user_id"),
        "session_analyses",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "weakness_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("skill_key", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=20), server_default="new", nullable=False),
        sa.Column("clean_streak", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_session_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('grammar', 'vocabulary', 'fluency', 'task_completion')",
            name="ck_weakness_records_category",
        ),
        sa.CheckConstraint(
            "state IN ('new', 'active', 'probation', 'mastered')",
            name="ck_weakness_records_state",
        ),
        sa.ForeignKeyConstraint(
            ["last_session_id"], ["learning_sessions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "category", "skill_key", name="uq_weakness_records_user_skill"
        ),
    )
    op.create_index(
        op.f("ix_weakness_records_user_id"),
        "weakness_records",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weakness_records_user_id"), table_name="weakness_records")
    op.drop_table("weakness_records")
    op.drop_index(op.f("ix_session_analyses_user_id"), table_name="session_analyses")
    op.drop_table("session_analyses")
    op.drop_index(op.f("ix_persona_memories_user_id"), table_name="persona_memories")
    op.drop_table("persona_memories")
    op.drop_index(op.f("ix_learning_sessions_user_id"), table_name="learning_sessions")
    op.drop_table("learning_sessions")
    # ### end Alembic commands ###
